version: '2'

services:
    log-service-1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: log-service-1
        ports:
            - "35001:6000"  # Mapea el puerto interno al puerto externo
        environment:
            - SERVER_PORT=6000

    log-service-2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: log-service-2
        ports:
            - "35002:6000"
        environment:
            - SERVER_PORT=6000

    log-service-3:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: log-service-3
        ports:
            - "35003:6000"
        environment:
            - SERVER_PORT=6000

    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod

volumes:
    mongodb:
    mongodb_config:
